[versions]
kotlin        = "2.1.21"
shadow        = "9.6.1"
mavenPublish  = "0.35.0"
gson          = "2.11.0"
snakeyaml     = "2.3"
junit         = "5.11.4"
mockito       = "5.20.0"
spigot18      = "1.8.8-R0.1-SNAPSHOT"
paper116      = "1.16.5-R0.1-SNAPSHOT"
paper1204     = "1.20.4-R0.1-SNAPSHOT"
paper121      = "1.21.11-R0.1-SNAPSHOT"
bungeecord    = "1.21-R0.4"
velocity      = "3.3.0-SNAPSHOT"

[libraries]
kotlin-stdlib       = { module = "org.jetbrains.kotlin:kotlin-stdlib",               version.ref = "kotlin" }
kotlin-reflect      = { module = "org.jetbrains.kotlin:kotlin-reflect",              version.ref = "kotlin" }
gson                = { module = "com.google.code.gson:gson",                         version.ref = "gson"   }
snakeyaml           = { module = "org.yaml:snakeyaml",                               version.ref = "snakeyaml" }
junit-jupiter       = { module = "org.junit.jupiter:junit-jupiter",                  version.ref = "junit"  }
junit-launcher      = { module = "org.junit.platform:junit-platform-launcher",       version = "1.11.4"     }
mockito-core        = { module = "org.mockito:mockito-core",                         version.ref = "mockito" }
mockito-kotlin      = { module = "org.mockito.kotlin:mockito-kotlin",                version = "5.4.0"      }
spigot-api-v18      = { module = "org.spigotmc:spigot-api",                          version.ref = "spigot18" }
paper-api-v116      = { module = "com.destroystokyo.paper:paper-api",                version.ref = "paper116" }
paper-api-v1204     = { module = "io.papermc.paper:paper-api",                       version.ref = "paper1204" }
paper-api-v121      = { module = "io.papermc.paper:paper-api",                       version.ref = "paper121" }
bungeecord-api      = { module = "net.md-5:bungeecord-api",                          version.ref = "bungeecord" }
velocity-api        = { module = "com.velocitypowered:velocity-api",                 version.ref = "velocity" }

[plugins]
kotlin-jvm    = { id = "org.jetbrains.kotlin.jvm",             version.ref = "kotlin" }
shadow        = { id = "com.gradleup.shadow",                  version.ref = "shadow" }
maven-publish = { id = "com.vanniktech.maven.publish",         version.ref = "mavenPublish" }
