[versions]
kotlin        = "2.1.21"
shadow        = "9.6.1"
gson          = "2.11.0"
snakeyaml     = "2.3"
junit         = "5.11.4"
mockito       = "5.20.0"
spigot18      = "1.8.8-R0.1-SNAPSHOT"
bungeecord    = "1.21-R0.4"
velocity      = "3.3.0-SNAPSHOT"

[libraries]
kotlin-stdlib       = { module = "org.jetbrains.kotlin:kotlin-stdlib",               version.ref = "kotlin" }
gson                = { module = "com.google.code.gson:gson",                         version.ref = "gson"   }
snakeyaml           = { module = "org.yaml:snakeyaml",                               version.ref = "snakeyaml" }
junit-jupiter       = { module = "org.junit.jupiter:junit-jupiter",                  version.ref = "junit"  }
junit-launcher      = { module = "org.junit.platform:junit-platform-launcher",       version = "1.11.4"     }
mockito-core        = { module = "org.mockito:mockito-core",                         version.ref = "mockito" }
mockito-kotlin      = { module = "org.mockito.kotlin:mockito-kotlin",                version = "5.4.0"      }
spigot-api-v18      = { module = "org.spigotmc:spigot-api",                          version.ref = "spigot18" }
bungeecord-api      = { module = "net.md-5:bungeecord-api",                          version.ref = "bungeecord" }
velocity-api        = { module = "com.velocitypowered:velocity-api",                 version.ref = "velocity" }

[plugins]
kotlin-jvm  = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow      = { id = "com.gradleup.shadow",        version.ref = "shadow" }
