package ru.privatenull.pnlibrary.core

import ru.privatenull.pnlibrary.core.observability.report.SystemReportCollector
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Assertions.assertTrue

class SystemReportCollectorTest {

    @Test
    fun `collect exposes derived runtime analytics`() {
        val report = SystemReportCollector().collect()

        val analytics = report["analytics"] as? Map<*, *>
            ?: error("analytics section is missing")
        assertTrue(analytics["resources"] is Map<*, *>)
        assertTrue(analytics["signals"] is List<*>)
        assertTrue(analytics["counts"] is Map<*, *>)
        assertTrue(analytics.containsKey("generatedUtc"))

        val runtimeDistribution = analytics["runtimeDistribution"] as? Map<*, *>
            ?: error("runtimeDistribution section is missing")
        assertTrue(runtimeDistribution.containsKey("uptimeSeconds"))
        assertTrue(runtimeDistribution.containsKey("classPathEntryCount"))
        assertTrue(runtimeDistribution.containsKey("systemPropertyCount"))
        assertTrue((analytics["signalSummary"] as? Map<*, *>)?.containsKey("critical") == true)
        assertTrue((analytics["coverage"] as? Map<*, *>)?.containsKey("javaRuntime") == true)
        assertTrue((analytics["coverage"] as? Map<*, *>)?.containsKey("processScheduling") == true)
        assertTrue(analytics["unavailableSections"] is List<*>)
        assertTrue((analytics["resources"] as? Map<*, *>)?.containsKey("processTcpEstablished") == true)
        assertTrue((analytics["resources"] as? Map<*, *>)?.containsKey("blockedThreads") == true)
        assertTrue((analytics["resources"] as? Map<*, *>)?.containsKey("loadAverage") == true)
        assertTrue((analytics["resources"] as? Map<*, *>)?.containsKey("processRss") == true)
        assertTrue((analytics["resources"] as? Map<*, *>)?.containsKey("voluntaryContextSwitches") == true)
        assertTrue((analytics["resources"] as? Map<*, *>)?.containsKey("blockedTimeMs") == true)
        assertTrue((analytics["resources"] as? Map<*, *>)?.containsKey("freeSpaceBytes") == true)
        assertTrue((analytics["resources"] as? Map<*, *>)?.containsKey("processVirtualMemory") == true)
        assertTrue((analytics["resources"] as? Map<*, *>)?.containsKey("processRssBytes") == true)
        assertTrue((analytics["resources"] as? Map<*, *>)?.containsKey("processNativeThreadCount") == true)
        assertTrue((analytics["resources"] as? Map<*, *>)?.containsKey("processPriority") == true)
        assertTrue((analytics["resources"] as? Map<*, *>)?.containsKey("totalSpaceBytes") == true)
        assertTrue((analytics["resources"] as? Map<*, *>)?.containsKey("fileSystemTypeCounts") == true)
        assertTrue((analytics["resources"] as? Map<*, *>)?.containsKey("swapUsedRatio") == true)
        val host = analytics["hostDistribution"] as? Map<*, *>
            ?: error("hostDistribution section is missing")
        assertTrue(host.containsKey("availableProcessors"))
        assertTrue(host.containsKey("totalPhysicalMemoryBytes"))
        assertTrue(host.containsKey("hostUptimeSeconds"))
        val limits = analytics["containerLimits"] as? Map<*, *>
            ?: error("containerLimits section is missing")
        assertTrue(limits.containsKey("memoryLimitBytes"))
        assertTrue(limits.containsKey("cpuQuotaMicros"))
        assertTrue(limits.containsKey("cpuThrottledMicros"))
        assertTrue(limits.containsKey("cpuThrottleEvents"))
        assertTrue(limits.containsKey("memoryOomKillEvents"))
        assertTrue(limits.containsKey("memoryUsedRatio"))
        assertTrue(limits.containsKey("cpuQuotaCores"))
        val collectionHistory = analytics["collectionHistory"] as? Map<*, *>
            ?: error("collectionHistory section is missing")
        assertTrue(collectionHistory.containsKey("samplesWithSignals"))
        assertTrue(collectionHistory.containsKey("signalCodeFrequency"))
        assertTrue((collectionHistory["trend"] as? Map<*, *>)?.containsKey("heapUsedRatioDelta") == true)
        assertTrue((collectionHistory["trend"] as? Map<*, *>)?.containsKey("systemCpuLoadDelta") == true)
        assertTrue((collectionHistory["trend"] as? Map<*, *>)?.containsKey("readBytesDelta") == true)
        assertTrue((collectionHistory["trend"] as? Map<*, *>)?.containsKey("tcpEstablishedDelta") == true)
        assertTrue((collectionHistory["trend"] as? Map<*, *>)?.containsKey("containerCpuThrottledDelta") == true)
        assertTrue((collectionHistory["trend"] as? Map<*, *>)?.containsKey("gcCollectionTimeMsDelta") == true)
        assertTrue((collectionHistory["trend"] as? Map<*, *>)?.containsKey("threadCountDelta") == true)
        assertTrue((collectionHistory["trend"] as? Map<*, *>)?.containsKey("heapUsedBytesDelta") == true)
        assertTrue((collectionHistory["trend"] as? Map<*, *>)?.containsKey("freePhysicalMemoryBytesDelta") == true)
        assertTrue((collectionHistory["trend"] as? Map<*, *>)?.containsKey("processRssDelta") == true)
        assertTrue((collectionHistory["trend"] as? Map<*, *>)?.containsKey("blockedThreadsDelta") == true)
        assertTrue((collectionHistory["trend"] as? Map<*, *>)?.containsKey("highestMemoryPoolRatioDelta") == true)
        assertTrue((collectionHistory["trend"] as? Map<*, *>)?.containsKey("unloadedClassCountDelta") == true)
        assertTrue((collectionHistory["trend"] as? Map<*, *>)?.containsKey("fileDescriptorOpenDelta") == true)
        assertTrue((collectionHistory["trend"] as? Map<*, *>)?.containsKey("hostUptimeSecondsDelta") == true)
        assertTrue((collectionHistory["trend"] as? Map<*, *>)?.containsKey("containerMemoryOomKillEventsDelta") == true)
        assertTrue((collectionHistory["trend"] as? Map<*, *>)?.containsKey("blockedTimeMsDelta") == true)
        assertTrue((collectionHistory["trend"] as? Map<*, *>)?.containsKey("unixSocketsDelta") == true)
        assertTrue((collectionHistory["trend"] as? Map<*, *>)?.containsKey("processPssBytesDelta") == true)
        assertTrue((collectionHistory["trend"] as? Map<*, *>)?.containsKey("openFileDescriptorCountDelta") == true)
        val network = report["networkAnalytics"] as? Map<*, *>
            ?: error("networkAnalytics section is missing")
        assertTrue(network.containsKey("ipv4AddressCount"))
        assertTrue(network.containsKey("ipv6AddressCount"))
        assertTrue(report["processIo"] is Map<*, *>)
        assertTrue(report["loadAverage"] is Map<*, *>)
        (report["loadAverage"] as? Map<*, *>)?.takeIf { it.isNotEmpty() }?.let {
            assertTrue(it.containsKey("oneMinutePerProcessor"))
        }
        assertTrue(report["processNetwork"] is Map<*, *>)
        assertTrue((report["processNetwork"] as? Map<*, *>)?.containsKey("tcpStateCounts") == true)
        assertTrue((report["processNetwork"] as? Map<*, *>)?.containsKey("udpStateCounts") == true)
        assertTrue((report["processNetwork"] as? Map<*, *>)?.containsKey("unixSockets") == true)
        assertTrue(report["processMemoryMaps"] is Map<*, *>)
        assertTrue(report["processFileDescriptors"] is Map<*, *>)
        assertTrue(report["processAffinity"] is Map<*, *>)
        assertTrue(report["pressureStall"] is Map<*, *>)
        assertTrue(report["kernelLimits"] is Map<*, *>)
        assertTrue((report["os"] as? Map<*, *>)?.get("distribution") is Map<*, *>)
        assertTrue((report["runtimeEnvironment"] as? Map<*, *>)?.containsKey("effectiveCpuCount") == true)
        assertTrue(report["systemScheduling"] is Map<*, *>)
        assertTrue(report["systemMemory"] is Map<*, *>)
        assertTrue((report["memory"] as? Map<*, *>)?.get("bufferPools") is List<*>)
        assertTrue(((report["memory"] as? Map<*, *>)?.get("pools") as? List<*>)?.firstOrNull() is Map<*, *> ||
            ((report["memory"] as? Map<*, *>)?.get("pools") as? List<*>)?.isEmpty() == true)
        assertTrue(report["jitCompilation"] is Map<*, *>)
        assertTrue((report["java"] as? Map<*, *>)?.get("classpathAnalytics") is Map<*, *>)
        assertTrue((report["threads"] as? Map<*, *>)?.get("analytics") is Map<*, *>)
        assertTrue((report["networkAnalytics"] as? Map<*, *>)?.containsKey("totalReceiveErrors") == true)
        assertTrue(report["mounts"] is Map<*, *>)
        assertTrue((analytics["resources"] as? Map<*, *>)?.containsKey("processPssBytes") == true)
        assertTrue((analytics["resources"] as? Map<*, *>)?.containsKey("processTcpStateCounts") == true)
        assertTrue((analytics["resources"] as? Map<*, *>)?.containsKey("processUdpStateCounts") == true)
        assertTrue((analytics["resources"] as? Map<*, *>)?.containsKey("openFileDescriptorCount") == true)
        assertTrue((analytics["resources"] as? Map<*, *>)?.containsKey("processFileDescriptorUsedRatio") == true)
        assertTrue((analytics["resources"] as? Map<*, *>)?.containsKey("pressureStall") == true)
        assertTrue((analytics["resources"] as? Map<*, *>)?.containsKey("kernelLimits") == true)
        assertTrue((analytics["resources"] as? Map<*, *>)?.containsKey("systemScheduling") == true)
        assertTrue((analytics["resources"] as? Map<*, *>)?.containsKey("systemMemory") == true)
        assertTrue((analytics["resources"] as? Map<*, *>)?.containsKey("containerEffectiveCpuCount") == true)
        assertTrue((analytics["hostDistribution"] as? Map<*, *>)?.containsKey("kernelRelease") == true)
        assertTrue((analytics["resources"] as? Map<*, *>)?.containsKey("bufferPoolUsedBytes") == true)
        assertTrue((analytics["resources"] as? Map<*, *>)?.containsKey("jitCompilationTimeMs") == true)
        assertTrue((analytics["resources"] as? Map<*, *>)?.containsKey("threadGroupCounts") == true)
        assertTrue((analytics["resources"] as? Map<*, *>)?.containsKey("networkReceiveBytes") == true)
        assertTrue((analytics["resources"] as? Map<*, *>)?.containsKey("mountTypeCounts") == true)
        assertTrue((analytics["resources"] as? Map<*, *>)?.containsKey("classpathMissingEntries") == true)
        assertTrue((analytics["resources"] as? Map<*, *>)?.containsKey("allowedCpuCount") == true)
        assertTrue((analytics["resources"] as? Map<*, *>)?.containsKey("memoryPoolPeakUsedBytes") == true)
        assertTrue(report["environmentVariableAnalytics"] is Map<*, *>)
        assertTrue(report["processStatus"] is Map<*, *>)
        assertTrue(report["processLimits"] is Map<*, *>)
        assertTrue(report["processScheduling"] is Map<*, *>)
        val health = report["health"] as? Map<*, *>
            ?: error("health section is missing")
        assertTrue(health.containsKey("physicalMemoryPressure"))
        assertTrue(health.containsKey("swapPressure"))
        assertTrue(health.containsKey("fileDescriptorPressure"))
        assertTrue(report["capabilities"] is Map<*, *>)
        assertTrue((analytics["capabilities"] as? Map<*, *>)?.containsKey("threadCpuTimeSupported") == true)
        assertTrue((analytics["resources"] as? Map<*, *>)?.containsKey("maxOpenFiles") == true)
        val threads = report["threads"] as? Map<*, *>
            ?: error("threads section is missing")
        val os = report["os"] as? Map<*, *>
            ?: error("os section is missing")
        assertTrue(os["cpuTopology"] is Map<*, *>)
        assertTrue((os["cpuTopology"] as? Map<*, *>)?.containsKey("physicalCoreCount") == true)
        val java = report["java"] as? Map<*, *>
            ?: error("java section is missing")
        assertTrue((java["classpathAnalytics"] as? Map<*, *>)?.containsKey("duplicateNameCount") == true)
        assertTrue((java["classpathAnalytics"] as? Map<*, *>)?.containsKey("duplicateNames") == true)
        assertTrue((java["modulePathAnalytics"] as? Map<*, *>)?.containsKey("entryCount") == true)
        assertTrue((java["argumentAnalytics"] as? Map<*, *>)?.containsKey("garbageCollectorOptions") == true)
        assertTrue(threads["deadlockedThreads"] is List<*>)
        assertTrue(threads["contention"] is Map<*, *>)
        (threads["topCpuThreads"] as? List<*>)?.firstOrNull()?.let { top ->
            assertTrue((top as? Map<*, *>)?.containsKey("cpuShare") == true)
        }
        val fileSystems = report["fileSystems"] as? List<*>
            ?: error("fileSystems section is missing")
        assertTrue(fileSystems.firstOrNull() is Map<*, *>)
        assertTrue((fileSystems.firstOrNull() as? Map<*, *>)?.containsKey("writable") == true)
    }
}
